[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
cloud_sol_treasury = "B3QEkbi6b6AAvXgUqpeWXBExVKYFEfU9psDqRdSgD76W"

[programs.localnet]
cloud_sol_treasury = "B3QEkbi6b6AAvXgUqpeWXBExVKYFEfU9psDqRdSgD76W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
#cluster = "Devnet"
#cluster = "Mainnet"

wallet = "/Users/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
